import fs from "node:fs";
import path from "node:path";
import { NextResponse } from "next/server";

const MIME: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".avif": "image/avif",
};

/** Serves portal uploads from data/uploads at runtime. */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ name: string }> },
) {
  const { name } = await params;
  const decoded = decodeURIComponent(name);
  // filenames are generated by the upload endpoint — anything else is rejected
  if (!/^[a-z0-9][a-z0-9.-]*$/i.test(decoded) || decoded.includes("..")) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
  const mime = MIME[path.extname(decoded).toLowerCase()];
  if (!mime) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
  const file = path.join(process.cwd(), "data", "uploads", decoded);
  if (!fs.existsSync(file)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }
  const buffer = fs.readFileSync(file);
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": mime,
      // names are timestamped, so they are safe to cache hard
      "Cache-Control": "public, max-age=31536000, immutable",
    },
  });
}
